services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
